spring:
  datasource:
    url: # enter jdbc url
    username: # enter username
    password: # enter password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: # enter schema name
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui/application
  api-docs:
    path: /api-docs

server:
  port: 4567


